"""
TriviaRush question pool.

Each question is one of:
  - {'type': 'mc',     'q': str, 'options': [4 strings], 'answer': int (index)}
  - {'type': 'older',  'q': 'Which is older?', 'a': str, 'b': str, 'answer': 'a'|'b', 'explain': str}
  - {'type': 'tf',     'q': str, 'answer': True|False, 'explain': str}

Categories: 'football', 'geography', 'movies', 'music', 'science', 'history', 'pop'

Curation principles:
  - NO 'What year did X happen' unless the year is genuinely surprising
  - NO 'capital of X' unless the country is non-obvious
  - Every question should make you go 'huh' or be a satisfying recall
  - Mix of difficulty
"""

QUESTIONS = [
    # ============================================================
    # FOOTBALL  (overlap with users' interest area)
    # ============================================================
    {'cat': 'football', 'type': 'mc',
     'q': 'Which country has won the most FIFA World Cups?',
     'options': ['Germany', 'Argentina', 'Brazil', 'Italy'],
     'answer': 2,
     'explain': 'Brazil with 5 (1958, 1962, 1970, 1994, 2002)'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Lionel Messi made his senior international debut against which country?',
     'options': ['Brazil', 'Hungary', 'Uruguay', 'Spain'],
     'answer': 1,
     'explain': '2005 vs Hungary — he was sent off within minutes'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Who is the all-time top scorer in the UEFA Champions League?',
     'options': ['Lionel Messi', 'Karim Benzema', 'Cristiano Ronaldo', 'Robert Lewandowski'],
     'answer': 2,
     'explain': 'Cristiano Ronaldo with 140+ goals'},
    {'cat': 'football', 'type': 'older',
     'q': 'Which club is older?', 'a': 'Real Madrid', 'b': 'Manchester United',
     'answer': 'b',
     'explain': 'Man United (1878), Real Madrid (1902)'},
    {'cat': 'football', 'type': 'older',
     'q': 'Which club is older?', 'a': 'Barcelona', 'b': 'Bayern Munich',
     'answer': 'a',
     'explain': 'Barcelona (1899), Bayern Munich (1900)'},
    {'cat': 'football', 'type': 'tf',
     'q': 'Cristiano Ronaldo has scored in 5 different World Cups.',
     'answer': True,
     'explain': '2006, 2010, 2014, 2018, 2022 — only player to do so'},
    {'cat': 'football', 'type': 'tf',
     'q': "Pelé scored over 1,000 career goals.",
     'answer': True,
     'explain': 'Officially 1,279 if you count all competitions including friendlies'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Which African country reached the World Cup semi-finals first?',
     'options': ['Cameroon', 'Senegal', 'Ghana', 'Morocco'],
     'answer': 3,
     'explain': 'Morocco in 2022 — first African and Arab nation in the World Cup semis'},
    {'cat': 'football', 'type': 'mc',
     'q': "What's the maximum number of substitutions allowed in a 90-minute league match (since 2022)?",
     'options': ['3', '4', '5', '7'],
     'answer': 2,
     'explain': '5, introduced during COVID and kept'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Which Premier League team has never been relegated since the league was founded in 1992?',
     'options': ['Liverpool', 'Manchester United', 'Arsenal', 'All of these'],
     'answer': 3,
     'explain': 'All three plus Chelsea, Tottenham, and Everton (Everton finally fell from "never relegated since 1954" but stayed in PL)'},
    {'cat': 'football', 'type': 'older',
     'q': 'Who is older?', 'a': 'Lionel Messi', 'b': 'Cristiano Ronaldo',
     'answer': 'b',
     'explain': 'Ronaldo (Feb 1985), Messi (Jun 1987)'},
    {'cat': 'football', 'type': 'mc',
     'q': "Erling Haaland's father, Alf-Inge, played for which Premier League club?",
     'options': ['Manchester City', 'Leeds United', 'Manchester United', 'Both Man City and Leeds'],
     'answer': 3,
     'explain': 'He played for both Leeds and Man City'},
    {'cat': 'football', 'type': 'tf',
     'q': "Mohamed Salah has won the African Cup of Nations.",
     'answer': False,
     'explain': 'Lost in the 2017 and 2021 finals'},
    {'cat': 'football', 'type': 'mc',
     'q': 'How many players are on the pitch at the start of a football match?',
     'options': ['20', '22', '24', '23'],
     'answer': 1,
     'explain': '11 per side'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Diego Maradona\'s famous "Hand of God" goal was against which country?',
     'options': ['Brazil', 'Belgium', 'England', 'West Germany'],
     'answer': 2,
     'explain': '1986 World Cup quarter-final vs England'},

    # ============================================================
    # GEOGRAPHY (interesting only)
    # ============================================================
    {'cat': 'geography', 'type': 'mc',
     'q': 'Which country has the most time zones?',
     'options': ['Russia', 'United States', 'France', 'China'],
     'answer': 2,
     'explain': 'France — 12 zones, counting overseas territories'},
    {'cat': 'geography', 'type': 'mc',
     'q': "Which African country was never colonized by Europeans?",
     'options': ['Egypt', 'Ethiopia', 'Liberia', 'Both Ethiopia and Liberia'],
     'answer': 3,
     'explain': 'Ethiopia resisted Italian colonization; Liberia was settled by freed slaves'},
    {'cat': 'geography', 'type': 'tf',
     'q': "Africa is the second-largest continent by area.",
     'answer': True,
     'explain': 'After Asia. About 30M km²'},
    {'cat': 'geography', 'type': 'mc',
     'q': "What is the largest country in Africa by area?",
     'options': ['Nigeria', 'Sudan', 'Algeria', 'D.R. Congo'],
     'answer': 2,
     'explain': 'Algeria — about 2.38M km²'},
    {'cat': 'geography', 'type': 'mc',
     'q': "What's the only country whose flag isn't rectangular?",
     'options': ['Switzerland', 'Vatican City', 'Nepal', 'Saudi Arabia'],
     'answer': 2,
     'explain': "Nepal — two stacked triangles"},
    {'cat': 'geography', 'type': 'older',
     'q': 'Which city is older?', 'a': 'Cairo', 'b': 'Rome',
     'answer': 'b',
     'explain': 'Rome founded 753 BC; Cairo founded 969 AD (the area was inhabited long before, but the city of Cairo is much newer)'},
    {'cat': 'geography', 'type': 'mc',
     'q': "Which country has the longest coastline in the world?",
     'options': ['Russia', 'Australia', 'Canada', 'Indonesia'],
     'answer': 2,
     'explain': 'Canada — ~202,000 km, mostly due to its arctic islands'},
    {'cat': 'geography', 'type': 'tf',
     'q': 'Australia is wider than the Moon is in diameter.',
     'answer': True,
     'explain': "Australia ~4000 km east-west; Moon ~3475 km diameter"},
    {'cat': 'geography', 'type': 'mc',
     'q': "What's the capital of Nigeria?",
     'options': ['Lagos', 'Abuja', 'Kano', 'Ibadan'],
     'answer': 1,
     'explain': 'Abuja — moved from Lagos in 1991'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Mount Kilimanjaro is in which country?',
     'options': ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'],
     'answer': 1,
     'explain': 'Tanzania (its peak is on the border but officially Tanzanian)'},
    {'cat': 'geography', 'type': 'older',
     'q': 'Which country is older?', 'a': 'Iceland', 'b': 'United States',
     'answer': 'a',
     'explain': "Iceland's parliament (Althing) dates to 930 AD"},
    {'cat': 'geography', 'type': 'mc',
     'q': "Through how many countries does the river Nile flow?",
     'options': ['4', '7', '11', '15'],
     'answer': 2,
     'explain': '11 — including Egypt, Sudan, Ethiopia, Uganda, Kenya, Tanzania, Rwanda, Burundi, DRC, South Sudan, Eritrea'},
    {'cat': 'geography', 'type': 'tf',
     'q': "Iceland has a McDonald's.",
     'answer': False,
     'explain': "The last McDonald's in Iceland closed in 2009"},

    # ============================================================
    # SCIENCE  (not "what's H2O")
    # ============================================================
    {'cat': 'science', 'type': 'mc',
     'q': 'How many bones does an adult human have?',
     'options': ['186', '206', '226', '246'],
     'answer': 1,
     'explain': '206 (babies have ~270 — many fuse over time)'},
    {'cat': 'science', 'type': 'tf',
     'q': 'A day on Venus is longer than a year on Venus.',
     'answer': True,
     'explain': 'Venus rotates so slowly that one day (~243 Earth days) > one orbit (~225)'},
    {'cat': 'science', 'type': 'mc',
     'q': 'What does DNA stand for?',
     'options': ['Diribonucleic acid', 'Deoxyribonucleic acid', 'Dinucleic acid', 'Disodium nucleic acid'],
     'answer': 1,
     'explain': 'Deoxyribonucleic acid'},
    {'cat': 'science', 'type': 'mc',
     'q': "What's the rarest blood type in humans?",
     'options': ['O negative', 'AB negative', 'B positive', 'AB positive'],
     'answer': 1,
     'explain': 'AB negative — about 0.6% of people'},
    {'cat': 'science', 'type': 'older',
     'q': 'Which is older?', 'a': 'Sharks', 'b': 'Trees',
     'answer': 'a',
     'explain': 'Sharks ~450M years; trees ~370M years'},
    {'cat': 'science', 'type': 'older',
     'q': 'Which is older?', 'a': 'The Great Pyramid', 'b': 'The Mammoth',
     'answer': 'b',
     'explain': 'Some woolly mammoths lived until ~4000 years ago — younger than the pyramid? Actually the last died on Wrangel Island ~2000 BC, around the same time. Some species lived alongside the pyramid builders'},
    {'cat': 'science', 'type': 'mc',
     'q': 'How many hearts does an octopus have?',
     'options': ['1', '2', '3', '8'],
     'answer': 2,
     'explain': '3 — one main, two for gills'},
    {'cat': 'science', 'type': 'tf',
     'q': "Bananas are berries, but strawberries aren't.",
     'answer': True,
     'explain': 'Botanically true — strawberries are "aggregate accessory fruits"'},
    {'cat': 'science', 'type': 'mc',
     'q': "What planet rotates on its side relative to its orbit?",
     'options': ['Mars', 'Saturn', 'Neptune', 'Uranus'],
     'answer': 3,
     'explain': "Uranus — axial tilt of ~98°"},
    {'cat': 'science', 'type': 'mc',
     'q': "What's the most abundant gas in Earth's atmosphere?",
     'options': ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'],
     'answer': 1,
     'explain': 'Nitrogen — about 78%'},
    {'cat': 'science', 'type': 'tf',
     'q': "Light from the Sun takes about 8 minutes to reach Earth.",
     'answer': True,
     'explain': '8 minutes 20 seconds'},
    {'cat': 'science', 'type': 'mc',
     'q': "Which is the most spoken first language in the world?",
     'options': ['English', 'Hindi', 'Spanish', 'Mandarin Chinese'],
     'answer': 3,
     'explain': 'Mandarin — ~920M native speakers'},

    # ============================================================
    # MOVIES & MUSIC
    # ============================================================
    {'cat': 'movies', 'type': 'mc',
     'q': 'Which film won Best Picture at the 2020 Oscars, the first non-English-language film to do so?',
     'options': ['Roma', 'Parasite', 'Drive My Car', 'Crouching Tiger, Hidden Dragon'],
     'answer': 1,
     'explain': 'Parasite (Korean) — directed by Bong Joon-ho'},
    {'cat': 'movies', 'type': 'older',
     'q': 'Which film is older?', 'a': 'Titanic', 'b': 'Jurassic Park',
     'answer': 'b',
     'explain': 'Jurassic Park (1993), Titanic (1997)'},
    {'cat': 'movies', 'type': 'mc',
     'q': 'In the Marvel Cinematic Universe, who played Thanos?',
     'options': ['Mark Ruffalo', 'Josh Brolin', 'Bradley Cooper', 'Vin Diesel'],
     'answer': 1,
     'explain': 'Josh Brolin (motion capture)'},
    {'cat': 'movies', 'type': 'tf',
     'q': "Avatar (2009) was the highest-grossing film of all time until Avengers: Endgame briefly took the title — then Avatar reclaimed it.",
     'answer': True,
     'explain': 'A 2021 re-release in China retook the box office crown'},
    {'cat': 'movies', 'type': 'mc',
     'q': 'Which director made "Pulp Fiction", "Kill Bill", and "Once Upon a Time in Hollywood"?',
     'options': ['Christopher Nolan', 'Quentin Tarantino', 'Martin Scorsese', 'David Fincher'],
     'answer': 1,
     'explain': 'Quentin Tarantino'},
    {'cat': 'music', 'type': 'mc',
     'q': "Which artist has the most monthly listeners on Spotify (as of recent data)?",
     'options': ['Taylor Swift', 'Bad Bunny', 'The Weeknd', 'Drake'],
     'answer': 2,
     'explain': "The Weeknd has held the top spot most months in 2024-25"},
    {'cat': 'music', 'type': 'older',
     'q': 'Which band is older?', 'a': 'The Rolling Stones', 'b': 'The Beatles',
     'answer': 'b',
     'explain': 'Beatles (1960), Rolling Stones (1962)'},
    {'cat': 'music', 'type': 'mc',
     'q': "What was Beyoncé's group called before her solo career?",
     'options': ["Destiny's Child", "The Supremes", "TLC", "Spice Girls"],
     'answer': 0,
     'explain': "Destiny's Child"},
    {'cat': 'music', 'type': 'tf',
     'q': "Burna Boy is from Lagos.",
     'answer': False,
     'explain': 'Born in Port Harcourt, Rivers State'},
    {'cat': 'music', 'type': 'mc',
     'q': "Which African artist's song 'Calm Down' became a global hit and got a remix with Selena Gomez?",
     'options': ['Davido', 'Wizkid', 'Rema', 'Burna Boy'],
     'answer': 2,
     'explain': "Rema, from Edo State, Nigeria"},

    # ============================================================
    # HISTORY  (not "when did WW1 start")
    # ============================================================
    {'cat': 'history', 'type': 'tf',
     'q': 'The shortest war in recorded history lasted under an hour.',
     'answer': True,
     'explain': 'Anglo-Zanzibar War, 1896 — about 38 minutes'},
    {'cat': 'history', 'type': 'mc',
     'q': "Which empire stretched the furthest at its peak?",
     'options': ['Roman', 'Mongol', 'British', 'Spanish'],
     'answer': 2,
     'explain': "British Empire — about 24% of Earth's land at its peak"},
    {'cat': 'history', 'type': 'older',
     'q': 'Which is older?', 'a': 'The pyramids of Giza', 'b': 'The Stonehenge',
     'answer': 'b',
     'explain': 'Stonehenge started around 3000 BC, Great Pyramid ~2560 BC'},
    {'cat': 'history', 'type': 'mc',
     'q': "Who was the first emperor of unified China?",
     'options': ['Kublai Khan', 'Qin Shi Huang', 'Sun Tzu', 'Confucius'],
     'answer': 1,
     'explain': 'Qin Shi Huang (221 BC) — also commissioned the Terracotta Army'},
    {'cat': 'history', 'type': 'tf',
     'q': "Oxford University is older than the Aztec Empire.",
     'answer': True,
     'explain': 'Oxford teaching from ~1096; Aztec Empire founded 1428'},
    {'cat': 'history', 'type': 'older',
     'q': 'Which independence is older?', 'a': "Ghana's independence", 'b': "Nigeria's independence",
     'answer': 'a',
     'explain': 'Ghana 1957, Nigeria 1960'},
    {'cat': 'history', 'type': 'mc',
     'q': 'Mansa Musa, considered one of the wealthiest people in history, ruled which empire?',
     'options': ['Songhai', 'Mali', 'Ghana', 'Kongo'],
     'answer': 1,
     'explain': "Mali Empire, 14th century"},

    # ============================================================
    # POP CULTURE
    # ============================================================
    {'cat': 'pop', 'type': 'mc',
     'q': "What's the most followed account on Instagram (as of 2024)?",
     'options': ['Selena Gomez', 'Cristiano Ronaldo', 'Lionel Messi', 'Kylie Jenner'],
     'answer': 1,
     'explain': "Cristiano Ronaldo — first to hit 600M followers"},
    {'cat': 'pop', 'type': 'tf',
     'q': "TikTok and Douyin are owned by the same company.",
     'answer': True,
     'explain': 'Both owned by ByteDance — Douyin is the China-only version'},
    {'cat': 'pop', 'type': 'mc',
     'q': "Which company owns WhatsApp, Instagram, and Facebook?",
     'options': ['Google', 'Meta', 'Microsoft', 'Apple'],
     'answer': 1,
     'explain': "Meta (formerly Facebook Inc.)"},
    {'cat': 'pop', 'type': 'mc',
     'q': "Bitcoin was created in 2009 by someone using which pseudonym?",
     'options': ['Vitalik Buterin', 'Satoshi Nakamoto', 'Hal Finney', 'Craig Wright'],
     'answer': 1,
     'explain': "Satoshi Nakamoto — true identity still unknown"},
    {'cat': 'pop', 'type': 'tf',
     'q': "ChatGPT was released to the public in 2022.",
     'answer': True,
     'explain': 'November 30, 2022'},
    {'cat': 'pop', 'type': 'mc',
     'q': "Which streaming series broke Netflix records in 2021, set in Korea, with players competing in deadly children's games?",
     'options': ['Money Heist', 'Squid Game', "All of Us Are Dead", "The Glory"],
     'answer': 1,
     'explain': "Squid Game"},
    {'cat': 'pop', 'type': 'older',
     'q': "Which company is older?", 'a': 'Microsoft', 'b': 'Apple',
     'answer': 'b',
     'explain': 'Apple founded April 1976; Microsoft April 1975 — actually Microsoft! (Microsoft was founded April 4 1975 by Gates & Allen; Apple April 1 1976. Microsoft is older.)'},

    # =========== APPENDED — large expansion ===========

    # === FOOTBALL ===
    {'cat': 'football', 'type': 'mc',
     'q': 'Which country won the 2022 FIFA World Cup?',
     'options': ['France', 'Argentina', 'Brazil', 'Croatia'],
     'answer': 1, 'explain': 'Argentina, 4-2 on penalties vs France'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Which club has won the most UEFA Champions League titles?',
     'options': ['Bayern Munich', 'Real Madrid', 'AC Milan', 'Liverpool'],
     'answer': 1, 'explain': 'Real Madrid with 15 (as of 2024)'},
    {'cat': 'football', 'type': 'mc',
     'q': "Who scored the 'Hand of God' goal?",
     'options': ['Pele', 'Maradona', 'Zidane', 'Ronaldinho'],
     'answer': 1, 'explain': '1986 World Cup quarter-final vs England'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Which country won Euro 2024?',
     'options': ['Spain', 'England', 'France', 'Germany'],
     'answer': 0, 'explain': 'Spain beat England 2-1 in the final'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Which player has won the most Ballon d\'Or awards?',
     'options': ['Messi', 'Ronaldo', 'Pele', 'Maradona'],
     'answer': 0, 'explain': "Messi with 8 (as of 2024)"},
    {'cat': 'football', 'type': 'tf',
     'q': 'Erling Haaland is Norwegian.',
     'answer': True, 'explain': 'Born in Leeds, plays for Norway'},
    {'cat': 'football', 'type': 'tf',
     'q': 'A football pitch must be exactly 100m long by FIFA rules.',
     'answer': False, 'explain': 'FIFA permits 90-120m length, 45-90m width'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Who is the all-time top scorer for the Brazilian national team?',
     'options': ['Pele', 'Neymar', 'Ronaldo', 'Ronaldinho'],
     'answer': 1, 'explain': 'Neymar passed Pele in 2023'},
    {'cat': 'football', 'type': 'older', 'q': 'Which club is older?',
     'a': 'Manchester United', 'b': 'Arsenal', 'answer': 'a',
     'explain': 'United 1878, Arsenal 1886'},
    {'cat': 'football', 'type': 'mc',
     'q': 'In what year was the first FIFA World Cup held?',
     'options': ['1924', '1930', '1934', '1928'],
     'answer': 1, 'explain': '1930 in Uruguay'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Who scored the most goals in a single World Cup tournament (men)?',
     'options': ['Pele', 'Muller', 'Just Fontaine', 'Klose'],
     'answer': 2, 'explain': 'Just Fontaine, 13 goals in 1958'},
    {'cat': 'football', 'type': 'tf',
     'q': 'The offside rule applies in your own half.',
     'answer': False, 'explain': 'You cannot be offside in your own half'},
    {'cat': 'football', 'type': 'mc',
     'q': 'How many players from one team are on a football pitch at kickoff?',
     'options': ['10', '11', '12', '9'],
     'answer': 1, 'explain': '11 including the goalkeeper'},
    {'cat': 'football', 'type': 'mc',
     'q': 'Which league does Bayern Munich play in?',
     'options': ['Bundesliga', 'La Liga', 'Serie A', 'Premier League'],
     'answer': 0, 'explain': 'German top flight'},
    {'cat': 'football', 'type': 'older', 'q': 'Which club is older?',
     'a': 'Liverpool', 'b': 'Chelsea', 'answer': 'a',
     'explain': 'Liverpool 1892, Chelsea 1905'},

    # === GEOGRAPHY ===
    {'cat': 'geography', 'type': 'mc',
     'q': 'What is the smallest country in the world by area?',
     'options': ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
     'answer': 1, 'explain': '0.49 sq km'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Which is the longest river in the world?',
     'options': ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
     'answer': 1, 'explain': 'Nile, ~6,650 km (Amazon disputed)'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Mount Everest lies on the border between which two countries?',
     'options': ['India and China', 'Nepal and China', 'Nepal and India', 'Bhutan and China'],
     'answer': 1, 'explain': 'Nepal-Tibet (China) border'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'What is the capital of Australia?',
     'options': ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
     'answer': 2, 'explain': 'Canberra was purpose-built as capital'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Which African country has the largest population?',
     'options': ['Egypt', 'Ethiopia', 'Nigeria', 'South Africa'],
     'answer': 2, 'explain': 'Nigeria, over 220 million'},
    {'cat': 'geography', 'type': 'tf',
     'q': 'The Sahara is the largest desert in the world.',
     'answer': False, 'explain': 'Antarctica is the largest desert by definition'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'In which ocean is the Bermuda Triangle?',
     'options': ['Pacific', 'Atlantic', 'Indian', 'Arctic'],
     'answer': 1, 'explain': 'North Atlantic, near Bermuda/Miami/Puerto Rico'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'What is the deepest ocean trench?',
     'options': ['Java', 'Mariana', 'Tonga', 'Puerto Rico'],
     'answer': 1, 'explain': 'Mariana Trench, ~11,000m deep'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Which is the largest country by area?',
     'options': ['Canada', 'USA', 'Russia', 'China'],
     'answer': 2, 'explain': 'Russia, ~17.1 million sq km'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'What is the currency of Japan?',
     'options': ['Yuan', 'Yen', 'Won', 'Ringgit'],
     'answer': 1, 'explain': 'Japanese Yen'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Which mountain range separates Europe and Asia?',
     'options': ['Alps', 'Caucasus', 'Urals', 'Pyrenees'],
     'answer': 2, 'explain': 'The Urals run through Russia'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'In which continent is the Atacama Desert?',
     'options': ['Africa', 'Asia', 'South America', 'Oceania'],
     'answer': 2, 'explain': 'Chile and Peru'},
    {'cat': 'geography', 'type': 'tf',
     'q': 'The Pacific Ocean is the largest ocean on Earth.',
     'answer': True, 'explain': 'Covers ~30% of Earth surface'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'What is the capital of Canada?',
     'options': ['Toronto', 'Montreal', 'Vancouver', 'Ottawa'],
     'answer': 3, 'explain': 'Ottawa, in Ontario'},
    {'cat': 'geography', 'type': 'older', 'q': 'Which city is older?',
     'a': 'Rome', 'b': 'London', 'answer': 'a',
     'explain': 'Rome 753 BC, London ~43 AD'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'How many continents are there (by the 7-continent model)?',
     'options': ['5', '6', '7', '8'], 'answer': 2,
     'explain': 'Africa, Antarctica, Asia, Australia, Europe, North America, South America'},
    {'cat': 'geography', 'type': 'mc',
     'q': 'Which country has the longest coastline?',
     'options': ['Russia', 'Canada', 'USA', 'Australia'],
     'answer': 1, 'explain': 'Canada, over 200,000 km'},
    {'cat': 'geography', 'type': 'tf',
     'q': 'Greenland is part of the European Union.',
     'answer': False, 'explain': 'Left in 1985; part of Denmark but not EU'},

    # === SCIENCE ===
    {'cat': 'science', 'type': 'mc',
     'q': 'What is the chemical symbol for gold?',
     'options': ['Go', 'Gd', 'Au', 'Ag'], 'answer': 2,
     'explain': "Au from Latin 'aurum'"},
    {'cat': 'science', 'type': 'mc',
     'q': 'How many bones are in the adult human body?',
     'options': ['206', '201', '215', '198'], 'answer': 0,
     'explain': '206; babies are born with around 270 that fuse'},
    {'cat': 'science', 'type': 'mc',
     'q': 'What gas do plants primarily absorb from the atmosphere?',
     'options': ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Methane'],
     'answer': 2, 'explain': 'CO2 for photosynthesis'},
    {'cat': 'science', 'type': 'tf',
     'q': 'Sound travels faster than light.',
     'answer': False, 'explain': 'Light is ~874,000x faster in air'},
    {'cat': 'science', 'type': 'mc',
     'q': 'Who developed the theory of relativity?',
     'options': ['Newton', 'Einstein', 'Hawking', 'Tesla'],
     'answer': 1, 'explain': 'Special relativity 1905, General 1915'},
    {'cat': 'science', 'type': 'mc',
     'q': 'Which planet has the most moons?',
     'options': ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
     'answer': 1, 'explain': 'Saturn, 146+ confirmed (as of 2024)'},
    {'cat': 'science', 'type': 'tf',
     'q': 'Water boils at 100 C at sea level.',
     'answer': True, 'explain': 'By definition of the Celsius scale'},
    {'cat': 'science', 'type': 'mc',
     'q': "What is the most abundant gas in Earth's atmosphere?",
     'options': ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
     'answer': 2, 'explain': 'Nitrogen ~78%'},
    {'cat': 'science', 'type': 'mc',
     'q': 'What is the largest organ in the human body?',
     'options': ['Liver', 'Brain', 'Skin', 'Lungs'],
     'answer': 2, 'explain': 'Skin covers ~1.8 sq m'},
    {'cat': 'science', 'type': 'mc',
     'q': 'Which element has atomic number 1?',
     'options': ['Helium', 'Hydrogen', 'Carbon', 'Oxygen'],
     'answer': 1, 'explain': 'Hydrogen, 1 proton'},
    {'cat': 'science', 'type': 'older', 'q': 'Which is older?',
     'a': 'Mt. Everest', 'b': 'Pyramids of Giza', 'answer': 'a',
     'explain': 'Everest ~60M years, Pyramids ~4500 years'},
    {'cat': 'science', 'type': 'mc',
     'q': 'Approximately how long does Earth take to orbit the Sun?',
     'options': ['355 days', '365 days', '375 days', '385 days'],
     'answer': 1, 'explain': '365.25 days'},
    {'cat': 'science', 'type': 'tf',
     'q': 'Humans share about 60% of their DNA with bananas.',
     'answer': True, 'explain': 'Often-cited fact comparing protein-coding genes'},
    {'cat': 'science', 'type': 'mc',
     'q': 'What does DNA stand for?',
     'options': ['Deoxyribonucleic Acid', 'Dinucleic Acid', 'Deoxy Nucleus Acid', 'Double Nucleotide Array'],
     'answer': 0, 'explain': 'The molecule encoding genetic instructions'},
    {'cat': 'science', 'type': 'mc',
     'q': 'Which scientist formulated the laws of motion?',
     'options': ['Galileo', 'Newton', 'Einstein', 'Bohr'],
     'answer': 1, 'explain': 'Newton, Principia 1687'},
    {'cat': 'science', 'type': 'mc',
     'q': 'What is the pH of pure water?',
     'options': ['5', '6', '7', '8'], 'answer': 2, 'explain': 'Neutral'},
    {'cat': 'science', 'type': 'mc',
     'q': 'Which is the closest star to Earth?',
     'options': ['Proxima Centauri', 'The Sun', 'Sirius', 'Alpha Centauri'],
     'answer': 1, 'explain': 'The Sun is itself a star'},
    {'cat': 'science', 'type': 'tf',
     'q': 'A year on Venus is shorter than a day on Venus.',
     'answer': True, 'explain': 'Venus rotates so slowly that one rotation > one orbit'},

    # === MOVIES ===
    {'cat': 'movies', 'type': 'mc',
     'q': 'Who directed Pulp Fiction?',
     'options': ['Spielberg', 'Tarantino', 'Scorsese', 'Nolan'],
     'answer': 1, 'explain': 'Quentin Tarantino, 1994'},
    {'cat': 'movies', 'type': 'mc',
     'q': "In Star Wars, what is the name of Luke Skywalker's father?",
     'options': ['Obi-Wan Kenobi', 'Han Solo', 'Anakin Skywalker / Darth Vader', 'Yoda'],
     'answer': 2, 'explain': 'Revealed in The Empire Strikes Back'},
    {'cat': 'movies', 'type': 'mc',
     'q': 'Which movie won Best Picture at the 2024 Oscars?',
     'options': ['Oppenheimer', 'Barbie', 'Killers of the Flower Moon', 'Poor Things'],
     'answer': 0, 'explain': "Christopher Nolan's Oppenheimer"},
    {'cat': 'movies', 'type': 'tf',
     'q': 'The Lord of the Rings trilogy was filmed in New Zealand.',
     'answer': True, 'explain': "Directed by Peter Jackson"},
    {'cat': 'movies', 'type': 'mc',
     'q': 'Who played the Joker in The Dark Knight (2008)?',
     'options': ['Joaquin Phoenix', 'Heath Ledger', 'Jared Leto', 'Jack Nicholson'],
     'answer': 1, 'explain': 'Ledger won a posthumous Oscar for the role'},
    {'cat': 'movies', 'type': 'mc',
     'q': 'Which animated film features a clownfish named Marlin?',
     'options': ['Finding Dory', 'Finding Nemo', 'Shark Tale', 'The Little Mermaid'],
     'answer': 1, 'explain': "Finding Nemo, 2003"},
    {'cat': 'movies', 'type': 'mc',
     'q': 'Who created the TV series Breaking Bad?',
     'options': ['Vince Gilligan', 'David Chase', 'Aaron Sorkin', 'Matthew Weiner'],
     'answer': 0, 'explain': "AMC, 2008-2013"},
    {'cat': 'movies', 'type': 'older', 'q': 'Which came out first?',
     'a': 'The Godfather', 'b': 'Star Wars', 'answer': 'a',
     'explain': 'Godfather 1972, Star Wars 1977'},
    {'cat': 'movies', 'type': 'mc',
     'q': 'What is the highest-grossing film of all time (worldwide)?',
     'options': ['Avatar (2009)', 'Avengers: Endgame', 'Titanic', 'Avatar: The Way of Water'],
     'answer': 0, 'explain': "Avatar reclaimed the top spot after re-releases"},

    # === MUSIC ===
    {'cat': 'music', 'type': 'mc',
     'q': 'Which band released "Bohemian Rhapsody"?',
     'options': ['The Beatles', 'Queen', 'Led Zeppelin', 'The Who'],
     'answer': 1, 'explain': '1975, written by Freddie Mercury'},
    {'cat': 'music', 'type': 'mc',
     'q': 'Who is known as the "King of Pop"?',
     'options': ['Elvis Presley', 'Michael Jackson', 'Prince', 'Stevie Wonder'],
     'answer': 1, 'explain': 'Michael Jackson'},
    {'cat': 'music', 'type': 'mc',
     'q': 'How many strings does a standard guitar have?',
     'options': ['4', '5', '6', '7'], 'answer': 2, 'explain': '6 strings: E A D G B E'},
    {'cat': 'music', 'type': 'tf',
     'q': "Beyonce was a member of Destiny's Child.",
     'answer': True, 'explain': 'Lead singer from 1990 until they split in 2006'},
    {'cat': 'music', 'type': 'mc',
     'q': 'Which artist released "Shape of You" in 2017?',
     'options': ['Justin Bieber', 'Ed Sheeran', 'Bruno Mars', 'Drake'],
     'answer': 1, 'explain': "From the album Divide"},
    {'cat': 'music', 'type': 'mc',
     'q': 'What instrument did Louis Armstrong primarily play?',
     'options': ['Saxophone', 'Trumpet', 'Piano', 'Clarinet'],
     'answer': 1, 'explain': "Jazz trumpet"},
    {'cat': 'music', 'type': 'older', 'q': 'Which album was released first?',
     'a': 'Thriller (Michael Jackson)', 'b': 'Dark Side of the Moon (Pink Floyd)',
     'answer': 'b', 'explain': 'Dark Side 1973, Thriller 1982'},
    {'cat': 'music', 'type': 'mc',
     'q': 'Which country is the Afrobeats genre most associated with?',
     'options': ['South Africa', 'Nigeria', 'Ghana', 'Kenya'],
     'answer': 1, 'explain': 'Nigeria, with artists like Burna Boy, Wizkid, Davido'},
    {'cat': 'music', 'type': 'mc',
     'q': 'Who composed "The Four Seasons"?',
     'options': ['Bach', 'Mozart', 'Vivaldi', 'Beethoven'],
     'answer': 2, 'explain': "Antonio Vivaldi, 1723"},

    # === HISTORY ===
    {'cat': 'history', 'type': 'mc',
     'q': 'In what year did World War II end?',
     'options': ['1943', '1944', '1945', '1946'], 'answer': 2,
     'explain': "VJ Day, Sept 2, 1945"},
    {'cat': 'history', 'type': 'mc',
     'q': 'Who was the first President of the United States?',
     'options': ['Jefferson', 'Adams', 'Washington', 'Lincoln'],
     'answer': 2, 'explain': 'George Washington, 1789'},
    {'cat': 'history', 'type': 'mc',
     'q': 'In what year did the Berlin Wall fall?',
     'options': ['1987', '1989', '1991', '1993'], 'answer': 1,
     'explain': 'November 9, 1989'},
    {'cat': 'history', 'type': 'tf',
     'q': 'Nelson Mandela was the first Black president of South Africa.',
     'answer': True, 'explain': 'Elected 1994 after his release'},
    {'cat': 'history', 'type': 'mc',
     'q': 'Which civilization built Machu Picchu?',
     'options': ['Aztec', 'Maya', 'Inca', 'Olmec'],
     'answer': 2, 'explain': 'Inca Empire, ~1450 AD'},
    {'cat': 'history', 'type': 'mc',
     'q': 'Who painted the ceiling of the Sistine Chapel?',
     'options': ['Da Vinci', 'Raphael', 'Michelangelo', 'Donatello'],
     'answer': 2, 'explain': 'Michelangelo, 1508-1512'},
    {'cat': 'history', 'type': 'mc',
     'q': 'In which year did the Titanic sink?',
     'options': ['1910', '1912', '1914', '1916'], 'answer': 1,
     'explain': 'April 14-15, 1912'},
    {'cat': 'history', 'type': 'tf',
     'q': 'The French Revolution began in 1789.',
     'answer': True, 'explain': 'Storming of the Bastille, July 14, 1789'},
    {'cat': 'history', 'type': 'mc',
     'q': 'Which African country was never formally colonised by Europeans?',
     'options': ['Kenya', 'Ethiopia', 'Ghana', 'Nigeria'],
     'answer': 1, 'explain': 'Ethiopia (briefly occupied by Italy 1936-41, but never formally colonised)'},

    # === POP CULTURE ===
    {'cat': 'pop', 'type': 'mc',
     'q': "What is the name of Harry Potter's pet owl?",
     'options': ['Errol', 'Hedwig', 'Crookshanks', 'Pigwidgeon'],
     'answer': 1, 'explain': 'Hedwig, a snowy owl'},
    {'cat': 'pop', 'type': 'mc',
     'q': 'In which fictional city does Batman operate?',
     'options': ['Metropolis', 'Gotham', 'Star City', 'Central City'],
     'answer': 1, 'explain': 'Gotham City'},
    {'cat': 'pop', 'type': 'tf',
     'q': 'Pikachu is an Electric-type Pokemon.',
     'answer': True, 'explain': 'Pokemon #25'},
    {'cat': 'pop', 'type': 'mc',
     'q': 'Who founded SpaceX?',
     'options': ['Bezos', 'Musk', 'Branson', 'Zuckerberg'],
     'answer': 1, 'explain': 'Elon Musk, 2002'},
    {'cat': 'pop', 'type': 'mc',
     'q': "What is TikTok's parent company?",
     'options': ['Tencent', 'ByteDance', 'Alibaba', 'Baidu'],
     'answer': 1, 'explain': 'ByteDance, founded 2012'},
    {'cat': 'pop', 'type': 'tf',
     'q': 'Bitcoin was created by Satoshi Nakamoto.',
     'answer': True, 'explain': 'Pseudonymous creator, 2008 whitepaper'},
    {'cat': 'pop', 'type': 'mc',
     'q': 'Which streaming service produced Stranger Things?',
     'options': ['HBO', 'Amazon Prime', 'Netflix', 'Disney+'],
     'answer': 2, 'explain': 'Netflix, premiered 2016'},
    {'cat': 'pop', 'type': 'older', 'q': 'Which is older?',
     'a': 'Twitter', 'b': 'Facebook', 'answer': 'b',
     'explain': 'Facebook 2004, Twitter 2006'},
    {'cat': 'pop', 'type': 'mc',
     'q': 'What animal is on the Lacoste logo?',
     'options': ['Crocodile', 'Alligator', 'Dragon', 'Lizard'],
     'answer': 0, 'explain': "Crocodile - tribute to Rene Lacoste's nickname"},
    {'cat': 'pop', 'type': 'mc',
     'q': "Who created the Sherlock Holmes character?",
     'options': ['Agatha Christie', 'Arthur Conan Doyle', 'Charles Dickens', 'Edgar Allan Poe'],
     'answer': 1, 'explain': "1887"},
]

# Fix the older-question above
for q in QUESTIONS:
    if q.get('q', '').startswith('Which company is older') and q.get('a') == 'Microsoft':
        q['answer'] = 'a'
        q['explain'] = 'Microsoft founded April 4 1975; Apple April 1 1976'

CATEGORY_LABELS = {
    'football': '⚽ Football',
    'geography': '🌍 Geography',
    'science': '🔬 Science',
    'movies': '🎬 Movies',
    'music': '🎵 Music',
    'history': '📜 History',
    'pop': '📱 Pop Culture',
}


def get_questions(n: int = 10, categories: list = None, exclude_ids: set = None):
    """Return n random questions, optionally filtered by categories and excluding seen ids."""
    import random as _r
    pool = QUESTIONS
    if categories:
        pool = [q for q in pool if q['cat'] in categories]
    if exclude_ids:
        pool = [q for q in pool if _question_id(q) not in exclude_ids]
    if not pool:
        # Fallback: ignore exclusions
        pool = [q for q in QUESTIONS if (not categories or q['cat'] in categories)]
    return _r.sample(pool, min(n, len(pool)))


def _question_id(q: dict) -> str:
    """Stable identifier so we can track seen-questions."""
    return q.get('q', '')[:60]


def question_to_public(q: dict) -> dict:
    """Strip the answer for client delivery (we check on server)."""
    base = {
        'id': _question_id(q),
        'cat': q['cat'],
        'cat_label': CATEGORY_LABELS.get(q['cat'], q['cat']),
        'type': q['type'],
        'q': q['q'],
    }
    if q['type'] == 'mc':
        base['options'] = q['options']
    elif q['type'] == 'older':
        base['a'] = q['a']
        base['b'] = q['b']
    # 'tf' has no extra fields
    return base


def check_answer(q_id: str, answer):
    """Return (correct: bool, the_correct_answer, explain: str)."""
    for q in QUESTIONS:
        if _question_id(q) == q_id:
            correct_ans = q['answer']
            explain = q.get('explain', '')
            if q['type'] == 'mc':
                # answer is index
                try: a = int(answer)
                except: a = -1
                return (a == correct_ans, correct_ans, explain)
            if q['type'] == 'older':
                return ((answer or '').lower() == correct_ans.lower(), correct_ans, explain)
            if q['type'] == 'tf':
                # answer is bool
                if isinstance(answer, str):
                    answer = answer.lower() in ('true', 't', '1', 'yes')
                return (bool(answer) == bool(correct_ans), correct_ans, explain)
    return (False, None, 'Question not found')


def total_count() -> int:
    return len(QUESTIONS)


# --- Admin content integration ---
# server.py calls refresh_admin_content() on boot and whenever the owner adds
# or deletes trivia via /admin. We keep the built-in questions as a permanent
# baseline and append admin items on top. Re-callable: it rebuilds the admin
# slice each time without duplicating.
_BUILTIN_COUNT = len(QUESTIONS)

def refresh_admin_content():
    """Re-sync QUESTIONS = builtin + current admin items. Safe to call often."""
    global QUESTIONS
    try:
        import admin_content
        # Reset to the built-in baseline, then merge admin items.
        builtin = QUESTIONS[:_BUILTIN_COUNT]
        QUESTIONS = admin_content.merged_trivia(builtin)
    except Exception as e:
        print(f"[trivia] refresh_admin_content failed: {e}")


def category_counts() -> dict:
    counts = {}
    for q in QUESTIONS:
        counts[q['cat']] = counts.get(q['cat'], 0) + 1
    return counts
